version: '3'

networks: 
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "${NGINX_PORT}:${NGINX_PORT_TO}"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - mysql
            - php
        networks: 
            - laravel

    mysql:
        image: mysql:latest
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: main
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports: 
            - "${MYSQL_PORT}:${MYSQL_PORT_TO}"
        volumes: 
            - ./mysql:/var/lib/mysql
        networks:
            - laravel

    php:
        build: 
            context: .
            dockerfile: DockerFile
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "${PHP_PORT}:${PHP_PORT_TO}"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql   
            - php
        ports: 
            - ${PHP_MY_ADMIN_PORT}:${PHP_MY_ADMIN_PORT_TO}
        networks:
            - laravel
        depends_on:
            - mysql
            - php
        environment: 
             - PMA_USER=${PMA_USER}
             - PMA_PASSWORD=${PMA_PASSWORD}
             - PMA_ARBITRARY=1
             - PMA_HOST=mysql

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - laravel
    